#!/usr/bin/env node
//
// LESS - Leaner CSS v@VERSION
// http://lesscss.org
// 
// Copyright (c) 2009-2011, Alexis Sellier
// Licensed under the Apache 2.0 License.
//
(function(D){function m(b){return b==="../lib/less"?r:b==="./parser"?r:b.indexOf(".")===0?r[b.split("/")[1]]:D(b)}exports.tree={};var g=exports.tree,r;if(typeof environment==="object"&&{}.toString.call(environment)==="[object Environment]")r=typeof window==="undefined"?{}:window.less={},g=r.tree={},r.mode="rhino";else if(typeof window==="undefined")r=exports,g=m("./tree"),r.mode="node";else{if(typeof window.less==="undefined")window.less={};r=window.less;g=window.less.tree={};r.mode="browser"}r.Parser=
function(b){function a(){w=s[q];x=i;v=i}function c(){s[q]=w;i=x;v=i}function f(){i>v&&(s[q]=s[q].slice(i-v),v=i)}function d(d){var a,b,c,h;if(d instanceof Function)return d.call(y.parsers);else if(typeof d==="string")d=j.charAt(i)===d?d:null,a=1,f();else if(f(),d=d.exec(s[q]))a=d[0].length;else return null;if(d){h=i+=a;for(c=i+s[q].length-a;i<c;){b=j.charCodeAt(i);if(!(b===32||b===10||b===9))break;i++}s[q]=s[q].slice(a+(i-h));v=i;s[q].length===0&&q<s.length-1&&q++;return typeof d==="string"?d:d.length===
1?d[0]:d}}function k(a,b){var c=d(a);if(c)return c;else h(b||(typeof a==="string"?"expected '"+a+"' got '"+j.charAt(i)+"'":"unexpected token"))}function h(d,a){throw{index:i,type:a||"Syntax",message:d};}function l(d){return typeof d==="string"?j.charAt(i)===d:d.test(s[q])?!0:!1}function n(d,a){for(var b=d,c=-1;b>=0&&a.charAt(b)!=="\n";b--)c++;return{line:typeof d==="number"?(a.slice(0,d).match(/\n/g)||"").length:null,column:c}}function o(d,a){var b=d.filename&&a.filename&&d.filename!==a.filename?
y.imports.contents[r.mode==="node"?m("path").basename(d.filename):d.filename.match(/[^\/]+$/)[0]]:j,c=n(d.index,b),h=c.line,c=c.column,f=b.split("\n");this.type=d.type||"Syntax";this.message=d.message;this.filename=d.filename||a.filename;this.index=d.index;this.line=typeof h==="number"?h+1:null;this.callLine=d.call&&n(d.call,b)+1;this.callExtract=f[n(d.call,b)];this.stack=d.stack;this.column=c;this.extract=[f[h-1],f[h],f[h+1]]}var j,i,q,w,x,z,s,v,y,C=function(){},B=this.imports={paths:b&&b.paths||
[],queue:[],files:{},contents:{},mime:b&&b.mime,error:null,push:function(d,a){var c=this;this.queue.push(d);r.Parser.importer(d,this.paths,function(b,h,f){c.queue.splice(c.queue.indexOf(d),1);c.files[d]=h;c.contents[d]=f;if(b&&!c.error)c.error=b;a(b,h);c.queue.length===0&&C()},b)}};this.env=b=b||{};this.optimization="optimization"in this.env?this.env.optimization:1;this.env.filename=this.env.filename||null;return y={imports:B,parse:function(a,c){var h,f,k,l=null;i=q=v=z=0;j=a.replace(/\r\n/g,"\n");
s=function(d){for(var a=0,c=/[^"'`\{\}\/\(\)\\]+/g,t=/\/\*(?:[^*]|\*+[^\/*])*\*+\/|\/\/.*/g,h=/"((?:[^"\\\r\n]|\\.)*)"|'((?:[^'\\\r\n]|\\.)*)'|`((?:[^`\\\r\n]|\\.)*)`/g,f=0,k,u=d[0],i,g=0,n,A;g<j.length;g++){c.lastIndex=g;if((k=c.exec(j))&&k.index===g)g+=k[0].length,u.push(k[0]);n=j.charAt(g);t.lastIndex=h.lastIndex=g;if((k=h.exec(j))&&k.index===g)g+=k[0].length,u.push(k[0]),n=j.charAt(g);if(!i&&n==="/"&&(A=j.charAt(g+1),A==="/"||A==="*"))if((k=t.exec(j))&&k.index===g)g+=k[0].length,u.push(k[0]),
n=j.charAt(g);switch(n){case "{":if(!i){f++;u.push(n);break}case "}":if(!i){f--;u.push(n);d[++a]=u=[];break}case "(":if(!i){i=!0;u.push(n);break}case ")":if(i){i=!1;u.push(n);break}default:u.push(n)}}f>0&&(l=new o({index:g,type:"Parse",message:"missing closing `}`",filename:b.filename},b));return d.map(function(d){return d.join("")})}([[]]);if(l)return c(l);try{h=new g.Ruleset([],d(this.parsers.primary)),h.root=!0}catch(n){return c(new o(n,b))}h.toCSS=function(d){return function(a,c){var t=[],a=a||
{};typeof c==="object"&&!Array.isArray(c)&&(c=Object.keys(c).map(function(d){var a=c[d];a instanceof g.Value||(a instanceof g.Expression||(a=new g.Expression([a])),a=new g.Value([a]));return new g.Rule("@"+d,a,!1,0)}),t=[new g.Ruleset(null,c)]);try{var h=d.call(this,{frames:t}).toCSS([],{compress:a.compress||!1})}catch(f){throw new o(f,b);}if(t=y.imports.error)if(t instanceof o)throw t;else throw new o(t,b);return a.yuicompress&&r.mode==="node"?m("./cssmin").compressor.cssmin(h):a.compress?h.replace(/(\s)+/g,
"$1"):h}}(h.eval);if(i<j.length-1){i=z;k=j.split("\n");f=(j.slice(0,i).match(/\n/g)||"").length+1;for(var w=i,x=-1;w>=0&&j.charAt(w)!=="\n";w--)x++;l={type:"Parse",message:"Syntax Error on line "+f,index:i,filename:b.filename,line:f,column:x,extract:[k[f-2],k[f-1],k[f]]}}this.imports.queue.length>0?C=function(){c(l,h)}:c(l,h)},parsers:{primary:function(){for(var a,c=[];(a=d(this.mixin.definition)||d(this.rule)||d(this.ruleset)||d(this.mixin.call)||d(this.comment)||d(this.directive))||d(/^[\s\n]+/);)a&&
c.push(a);return c},comment:function(){var a;if(j.charAt(i)==="/")if(j.charAt(i+1)==="/")return new g.Comment(d(/^\/\/.*/),!0);else if(a=d(/^\/\*(?:[^*]|\*+[^\/*])*\*+\/\n?/))return new g.Comment(a)},entities:{quoted:function(){var a;a=i;var c;j.charAt(a)==="~"&&(a++,c=!0);if(!(j.charAt(a)!=='"'&&j.charAt(a)!=="'")&&(c&&d("~"),a=d(/^"((?:[^"\\\r\n]|\\.)*)"|'((?:[^'\\\r\n]|\\.)*)'/)))return new g.Quoted(a[0],a[1]||a[2],c)},keyword:function(){var a;if(a=d(/^[_A-Za-z-][_A-Za-z0-9-]*/))return g.colors.hasOwnProperty(a)?
new g.Color(g.colors[a].slice(1)):new g.Keyword(a)},call:function(){var a,c,h=i;if(a=/^([\w-]+|%|progid:[\w\.]+)\(/.exec(s[q])){a=a[1].toLowerCase();if(a==="url")return null;else i+=a.length;if(a==="alpha")return d(this.alpha);d("(");c=d(this.entities.arguments);if(d(")")&&a)return new g.Call(a,c,h,b.filename)}},arguments:function(){for(var a=[],c;c=d(this.entities.assignment)||d(this.expression);)if(a.push(c),!d(","))break;return a},literal:function(){return d(this.entities.dimension)||d(this.entities.color)||
d(this.entities.quoted)},assignment:function(){var a,c;if((a=d(/^\w+(?=\s?=)/i))&&d("=")&&(c=d(this.entity)))return new g.Assignment(a,c)},url:function(){var a;if(j.charAt(i)==="u"&&d(/^url\(/))return a=d(this.entities.quoted)||d(this.entities.variable)||d(this.entities.dataURI)||d(/^[-\w%@$\/.&=:;#+?~]+/)||"",k(")"),new g.URL(a.value||a.data||a instanceof g.Variable?a:new g.Anonymous(a),B.paths)},dataURI:function(){var a;if(d(/^data:/)&&(a={},a.mime=d(/^[^\/]+\/[^,;)]+/)||"",a.charset=d(/^;\s*charset=[^,;)]+/)||
"",a.base64=d(/^;\s*base64/)||"",a.data=d(/^,\s*[^)]+/),a.data))return a},variable:function(){var a,c=i;if(j.charAt(i)==="@"&&(a=d(/^@@?[\w-]+/)))return new g.Variable(a,c,b.filename)},color:function(){var a;if(j.charAt(i)==="#"&&(a=d(/^#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})/)))return new g.Color(a[1])},dimension:function(){var a;a=j.charCodeAt(i);if(!(a>57||a<45||a===47))if(a=d(/^(-?\d*\.?\d+)(px|%|em|rem|pc|ex|in|deg|s|ms|pt|cm|mm|rad|grad|turn)?/))return new g.Dimension(a[1],a[2])},javascript:function(){var a;
a=i;var c;j.charAt(a)==="~"&&(a++,c=!0);if(j.charAt(a)==="`"&&(c&&d("~"),a=d(/^`([^`]*)`/)))return new g.JavaScript(a[1],i,c)}},variable:function(){var a;if(j.charAt(i)==="@"&&(a=d(/^(@[\w-]+)\s*:/)))return a[1]},shorthand:function(){var a,c;if(l(/^[@\w.%-]+\/[@\w.-]+/)&&(a=d(this.entity))&&d("/")&&(c=d(this.entity)))return new g.Shorthand(a,c)},mixin:{call:function(){var a=[],c,h,f,k=i;c=j.charAt(i);var n=!1;if(!(c!=="."&&c!=="#")){for(;c=d(/^[#.](?:[\w-]|\\(?:[a-fA-F0-9]{1,6} ?|[^a-fA-F0-9]))+/);)a.push(new g.Element(h,
c,i)),h=d(">");d("(")&&(f=d(this.entities.arguments))&&d(")");d(this.important)&&(n=!0);if(a.length>0&&(d(";")||l("}")))return new g.mixin.Call(a,f,k,b.filename,n)}},definition:function(){var b,h=[],f,n,o;if(!(j.charAt(i)!=="."&&j.charAt(i)!=="#"||l(/^[^{]*(;|})/)))if(a(),b=d(/^([#.](?:[\w-]|\\(?:[a-fA-F0-9]{1,6} ?|[^a-fA-F0-9]))+)\s*\(/)){for(b=b[1];f=d(this.entities.variable)||d(this.entities.literal)||d(this.entities.keyword);)if(f instanceof g.Variable?d(":")?(n=k(this.expression,"expected expression"),
h.push({name:f.name,value:n})):h.push({name:f.name}):h.push({value:f}),!d(","))break;k(")");d(/^when/)&&(o=k(this.conditions,"expected condition"));if(f=d(this.block))return new g.mixin.Definition(b,h,f,o);else c()}}},entity:function(){return d(this.entities.literal)||d(this.entities.variable)||d(this.entities.url)||d(this.entities.call)||d(this.entities.keyword)||d(this.entities.javascript)||d(this.comment)},end:function(){return d(";")||l("}")},alpha:function(){var a;if(d(/^\(opacity=/i)&&(a=d(/^\d+/)||
d(this.entities.variable)))return k(")"),new g.Alpha(a)},element:function(){var a,c,b;c=d(this.combinator);(a=d(/^(?:\d+\.\d+|\d+)%/)||d(/^(?:[.#]?|:*)(?:[\w-]|\\(?:[a-fA-F0-9]{1,6} ?|[^a-fA-F0-9]))+/)||d("*")||d(this.attribute)||d(/^\([^)@]+\)/))||d("(")&&(b=d(this.entities.variable))&&d(")")&&(a=new g.Paren(b));if(a)return new g.Element(c,a,i);if(c.value&&c.value.charAt(0)==="&")return new g.Element(c,null,i)},combinator:function(){var d;d=j.charAt(i);if(d===">"||d==="+"||d==="~"){for(i++;j.charAt(i)===
" ";)i++;return new g.Combinator(d)}else if(d==="&"){d="&";i++;for(j.charAt(i)===" "&&(d="& ");j.charAt(i)===" ";)i++;return new g.Combinator(d)}else if(d===":"&&j.charAt(i+1)===":"){for(i+=2;j.charAt(i)===" ";)i++;return new g.Combinator("::")}else return j.charAt(i-1)===" "?new g.Combinator(" "):new g.Combinator(null)},selector:function(){for(var a,c=[],b;a=d(this.element);)if(b=j.charAt(i),c.push(a),b==="{"||b==="}"||b===";"||b===",")break;if(c.length>0)return new g.Selector(c)},tag:function(){return d(/^[a-zA-Z][a-zA-Z-]*[0-9]?/)||
d("*")},attribute:function(){var a="",c,b,h;if(d("[")){if(c=d(/^[a-zA-Z-]+/)||d(this.entities.quoted))a=(h=d(/^[|~*$^]?=/))&&(b=d(this.entities.quoted)||d(/^[\w-]+/))?[c,h,b.toCSS?b.toCSS():b].join(""):c;if(d("]")&&a)return"["+a+"]"}},block:function(){var a;if(d("{")&&(a=d(this.primary))&&d("}"))return a},ruleset:function(){var b=[],h,f;for(a();h=d(this.selector);){b.push(h);d(this.comment);if(!d(","))break;d(this.comment)}if(b.length>0&&(f=d(this.block)))return new g.Ruleset(b,f);else z=i,c()},rule:function(){var b,
h;b=j.charAt(i);var f;a();if(!(b==="."||b==="#"||b==="&"))if(b=d(this.variable)||d(this.property))if(b.charAt(0)!="@"&&(h=/^([^@+\/'"*`(;{}-]*);/.exec(s[q]))?(i+=h[0].length-1,h=new g.Anonymous(h[1])):h=b==="font"?d(this.font):d(this.value),f=d(this.important),h&&d(this.end))return new g.Rule(b,h,f,x);else z=i,c()},"import":function(){var a,c,b=i;if(d(/^@import\s+/)&&(a=d(this.entities.quoted)||d(this.entities.url)))if(c=d(this.mediaFeatures),d(";"))return new g.Import(a,B,c,b)},mediaFeature:function(){var a=
[];do if(e=d(this.entities.keyword))a.push(e);else if(d("("))if(p=d(this.property),e=d(this.entity),d(")"))if(p&&e)a.push(new g.Paren(new g.Rule(p,e,null,i,!0)));else if(e)a.push(new g.Paren(e));else return null;else return null;while(e);if(a.length>0)return new g.Expression(a)},mediaFeatures:function(){for(var a,c=[];a=d(this.mediaFeature);)if(c.push(a),!d(","))break;return c.length>0?c:null},media:function(){var a;if(d(/^@media/)&&(a=d(this.mediaFeatures),rules=d(this.block)))return new g.Directive("@media",
rules,a)},directive:function(){var a,c,b;if(j.charAt(i)==="@")if(c=d(this["import"])||d(this.media))return c;else if(a=d(/^@page|@keyframes/)||d(/^@(?:-webkit-|-moz-|-o-|-ms-)[a-z0-9-]+/)){if(b=(d(/^[^{]+/)||"").trim(),c=d(this.block))return new g.Directive(a+" "+b,c)}else if(a=d(/^@[-a-z]+/))if(a==="@font-face"){if(c=d(this.block))return new g.Directive(a,c)}else if((c=d(this.entity))&&d(";"))return new g.Directive(a,c)},font:function(){for(var a=[],c=[],b;b=d(this.shorthand)||d(this.entity);)c.push(b);
a.push(new g.Expression(c));if(d(","))for(;b=d(this.expression);)if(a.push(b),!d(","))break;return new g.Value(a)},value:function(){for(var a,c=[];a=d(this.expression);)if(c.push(a),!d(","))break;if(c.length>0)return new g.Value(c)},important:function(){if(j.charAt(i)==="!")return d(/^! *important/)},sub:function(){var a;if(d("(")&&(a=d(this.expression))&&d(")"))return a},multiplication:function(){var a,c,b,h;if(a=d(this.operand)){for(;!l(/^\/\*/)&&(b=d("/")||d("*"))&&(c=d(this.operand));)h=new g.Operation(b,
[h||a,c]);return h||a}},addition:function(){var a,c,b,h;if(a=d(this.multiplication)){for(;(b=d(/^[-+]\s+/)||j.charAt(i-1)!=" "&&(d("+")||d("-")))&&(c=d(this.multiplication));)h=new g.Operation(b,[h||a,c]);return h||a}},conditions:function(){var a,c,b=i,h;if(a=d(this.condition)){for(;d(",")&&(c=d(this.condition));)h=new g.Condition("or",h||a,c,b);return h||a}},condition:function(){var a,c,b,f,l=i,j=!1;d(/^not/)&&(j=!0);k("(");if(a=d(this.addition)||d(this.entities.keyword)||d(this.entities.quoted))return(f=
d(/^(?:>=|=<|[<=>])/))?(c=d(this.addition)||d(this.entities.keyword)||d(this.entities.quoted))?b=new g.Condition(f,a,c,l,j):h("expected expression"):b=new g.Condition("=",a,new g.Keyword("true"),l,j),k(")"),d(/^and/)?new g.Condition("and",b,d(this.condition)):b},operand:function(){var a,c=j.charAt(i+1);if(j.charAt(i)==="-"&&(c==="@"||c==="("))a=d("-");c=d(this.sub)||d(this.entities.dimension)||d(this.entities.color)||d(this.entities.variable)||d(this.entities.call);return a?new g.Operation("*",[new g.Dimension(-1),
c]):c},expression:function(){for(var a,c=[];a=d(this.addition)||d(this.entity);)c.push(a);if(c.length>0)return new g.Expression(c)},property:function(){var a;if(a=d(/^(\*?-?[-a-z_0-9]+)\s*:/))return a[1]}}}};if(r.mode==="browser"||r.mode==="rhino")r.Parser.importer=function(b,a,c,f){!/^([a-z]+:)?\//.test(b)&&a.length>0&&(b=a[0]+b);loadStyleSheet({href:b,title:b,type:f.mime},function(d){d&&typeof f.errback==="function"?f.errback.call(null,b,a,c,f):c.apply(null,arguments)},!0)};(function(b){function a(a){return b.functions.hsla(a.h,
a.s,a.l,a.a)}function c(a){if(a instanceof b.Dimension)return parseFloat(a.unit=="%"?a.value/100:a.value);else if(typeof a==="number")return a;else throw{error:"RuntimeError",message:"color functions take numbers as parameters"};}function f(a){return Math.min(1,Math.max(0,a))}b.functions={rgb:function(a,c,b){return this.rgba(a,c,b,1)},rgba:function(a,f,h,l){a=[a,f,h].map(function(a){return c(a)});l=c(l);return new b.Color(a,l)},hsl:function(a,c,b){return this.hsla(a,c,b,1)},hsla:function(a,b,h,f){function g(a){a=
a<0?a+1:a>1?a-1:a;return a*6<1?j+(o-j)*a*6:a*2<1?o:a*3<2?j+(o-j)*(2/3-a)*6:j}var a=c(a)%360/360,b=c(b),h=c(h),f=c(f),o=h<=0.5?h*(b+1):h+b-h*b,j=h*2-o;return this.rgba(g(a+1/3)*255,g(a)*255,g(a-1/3)*255,f)},hue:function(a){return new b.Dimension(Math.round(a.toHSL().h))},saturation:function(a){return new b.Dimension(Math.round(a.toHSL().s*100),"%")},lightness:function(a){return new b.Dimension(Math.round(a.toHSL().l*100),"%")},alpha:function(a){return new b.Dimension(a.toHSL().a)},saturate:function(d,
c){var b=d.toHSL();b.s+=c.value/100;b.s=f(b.s);return a(b)},desaturate:function(d,c){var b=d.toHSL();b.s-=c.value/100;b.s=f(b.s);return a(b)},lighten:function(d,c){var b=d.toHSL();b.l+=c.value/100;b.l=f(b.l);return a(b)},darken:function(d,c){var b=d.toHSL();b.l-=c.value/100;b.l=f(b.l);return a(b)},fadein:function(d,c){var b=d.toHSL();b.a+=c.value/100;b.a=f(b.a);return a(b)},fadeout:function(d,c){var b=d.toHSL();b.a-=c.value/100;b.a=f(b.a);return a(b)},fade:function(d,c){var b=d.toHSL();b.a=c.value/
100;b.a=f(b.a);return a(b)},spin:function(d,c){var b=d.toHSL(),f=(b.h+c.value)%360;b.h=f<0?360+f:f;return a(b)},mix:function(a,c,f){var f=f.value/100,l=f*2-1,g=a.toHSL().a-c.toHSL().a,l=((l*g==-1?l:(l+g)/(1+l*g))+1)/2,g=1-l;return new b.Color([a.rgb[0]*l+c.rgb[0]*g,a.rgb[1]*l+c.rgb[1]*g,a.rgb[2]*l+c.rgb[2]*g],a.alpha*f+c.alpha*(1-f))},greyscale:function(a){return this.desaturate(a,new b.Dimension(100))},e:function(a){return new b.Anonymous(a instanceof b.JavaScript?a.evaluated:a)},escape:function(a){return new b.Anonymous(encodeURI(a.value).replace(/=/g,
"%3D").replace(/:/g,"%3A").replace(/#/g,"%23").replace(/;/g,"%3B").replace(/\(/g,"%28").replace(/\)/g,"%29"))},"%":function(a){for(var c=Array.prototype.slice.call(arguments,1),f=a.value,l=0;l<c.length;l++)f=f.replace(/%[sda]/i,function(a){var d=a.match(/s/i)?c[l].value:c[l].toCSS();return a.match(/[A-Z]$/)?encodeURIComponent(d):d});f=f.replace(/%%/g,"%");return new b.Quoted('"'+f+'"',f)},round:function(a){return this._math("round",a)},ceil:function(a){return this._math("ceil",a)},floor:function(a){return this._math("floor",
a)},_math:function(a,f){if(f instanceof b.Dimension)return new b.Dimension(Math[a](c(f)),f.unit);else if(typeof f==="number")return Math[a](f);else throw{type:"Argument",message:"argument must be a number"};},argb:function(a){return new b.Anonymous(a.toARGB())},percentage:function(a){return new b.Dimension(a.value*100,"%")},color:function(a){if(a instanceof b.Quoted)return new b.Color(a.value.slice(1));else throw{type:"Argument",message:"argument must be a string"};},iscolor:function(a){return this._isa(a,
b.Color)},isnumber:function(a){return this._isa(a,b.Dimension)},isstring:function(a){return this._isa(a,b.Quoted)},iskeyword:function(a){return this._isa(a,b.Keyword)},isurl:function(a){return this._isa(a,b.URL)},ispixel:function(a){return a instanceof b.Dimension&&a.unit==="px"?b.True:b.False},ispercentage:function(a){return a instanceof b.Dimension&&a.unit==="%"?b.True:b.False},isem:function(a){return a instanceof b.Dimension&&a.unit==="em"?b.True:b.False},_isa:function(a,c){return a instanceof
c?b.True:b.False}}})(m("./tree"));(function(b){b.colors={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",
darkgray:"#a9a9a9",darkgrey:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",
fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",grey:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgrey:"#d3d3d3",lightgreen:"#90ee90",
lightpink:"#ffb6c1",lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",
mintcream:"#f5fffa",mistyrose:"#ffe4e1",moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",
sandybrown:"#f4a460",seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"}})(m("./tree"));(function(b){b.Alpha=function(a){this.value=a};b.Alpha.prototype=
{toCSS:function(){return"alpha(opacity="+(this.value.toCSS?this.value.toCSS():this.value)+")"},eval:function(a){if(this.value.eval)this.value=this.value.eval(a);return this}}})(m("../tree"));(function(b){b.Anonymous=function(a){this.value=a.value||a};b.Anonymous.prototype={toCSS:function(){return this.value},eval:function(){return this}}})(m("../tree"));(function(b){b.Assignment=function(a,c){this.key=a;this.value=c};b.Assignment.prototype={toCSS:function(){return this.key+"="+(this.value.toCSS?this.value.toCSS():
this.value)},eval:function(a){if(this.value.eval)this.value=this.value.eval(a);return this}}})(m("../tree"));(function(b){b.Call=function(a,c,b,d){this.name=a;this.args=c;this.index=b;this.filename=d};b.Call.prototype={eval:function(a){var c=this.args.map(function(c){return c.eval(a)});if(this.name in b.functions)try{return b.functions[this.name].apply(b.functions,c)}catch(f){throw{type:f.type||"Runtime",message:"error evaluating function `"+this.name+"`"+(f.message?": "+f.message:""),index:this.index,
filename:this.filename};}else return new b.Anonymous(this.name+"("+c.map(function(a){return a.toCSS()}).join(", ")+")")},toCSS:function(a){return this.eval(a).toCSS()}}})(m("../tree"));(function(b){b.Color=function(a,c){this.rgb=Array.isArray(a)?a:a.length==6?a.match(/.{2}/g).map(function(a){return parseInt(a,16)}):a.split("").map(function(a){return parseInt(a+a,16)});this.alpha=typeof c==="number"?c:1};b.Color.prototype={eval:function(){return this},toCSS:function(){return this.alpha<1?"rgba("+this.rgb.map(function(a){return Math.round(a)}).concat(this.alpha).join(", ")+
")":"#"+this.rgb.map(function(a){a=Math.round(a);a=(a>255?255:a<0?0:a).toString(16);return a.length===1?"0"+a:a}).join("")},operate:function(a,c){var f=[];c instanceof b.Color||(c=c.toColor());for(var d=0;d<3;d++)f[d]=b.operate(a,this.rgb[d],c.rgb[d]);return new b.Color(f,this.alpha+c.alpha)},toHSL:function(){var a=this.rgb[0]/255,c=this.rgb[1]/255,b=this.rgb[2]/255,d=this.alpha,k=Math.max(a,c,b),h=Math.min(a,c,b),l,g=(k+h)/2,o=k-h;if(k===h)l=h=0;else{h=g>0.5?o/(2-k-h):o/(k+h);switch(k){case a:l=
(c-b)/o+(c<b?6:0);break;case c:l=(b-a)/o+2;break;case b:l=(a-c)/o+4}l/=6}return{h:l*360,s:h,l:g,a:d}},toARGB:function(){return"#"+[Math.round(this.alpha*255)].concat(this.rgb).map(function(a){a=Math.round(a);a=(a>255?255:a<0?0:a).toString(16);return a.length===1?"0"+a:a}).join("")}}})(m("../tree"));(function(b){b.Comment=function(a,c){this.value=a;this.silent=!!c};b.Comment.prototype={toCSS:function(a){return a.compress?"":this.value},eval:function(){return this}}})(m("../tree"));(function(b){b.Condition=
function(a,c,b,d,k){this.op=a.trim();this.lvalue=c;this.rvalue=b;this.index=d;this.negate=k};b.Condition.prototype.eval=function(a){var c=this.lvalue.eval(a),b=this.rvalue.eval(a),d=this.index,k;k=function(a){switch(a){case "and":return c&&b;case "or":return c||b;default:if(c.compare)k=c.compare(b);else if(b.compare)k=b.compare(c);else throw{type:"Type",message:"Unable to perform comparison",index:d};switch(k){case -1:return a==="<"||a==="=<";case 0:return a==="="||a===">="||a==="=<";case 1:return a===
">"||a===">="}}}(this.op);return this.negate?!k:k}})(m("../tree"));(function(b){b.Dimension=function(a,c){this.value=parseFloat(a);this.unit=c||null};b.Dimension.prototype={eval:function(){return this},toColor:function(){return new b.Color([this.value,this.value,this.value])},toCSS:function(){return this.value+this.unit},operate:function(a,c){return new b.Dimension(b.operate(a,this.value,c.value),this.unit||c.unit)},compare:function(a){return a instanceof b.Dimension?a.value>this.value?-1:a.value<
this.value?1:0:-1}}})(m("../tree"));(function(b){b.Directive=function(a,c,f){this.name=a;this.features=f&&new b.Value(f);Array.isArray(c)?(this.ruleset=new b.Ruleset([],c),this.ruleset.allowImports=!0):this.value=c};b.Directive.prototype={toCSS:function(a,c){var b=this.features?" "+this.features.toCSS(c):"";return this.ruleset?(this.ruleset.root=!0,this.name+b+(c.compress?"{":" {\n  ")+this.ruleset.toCSS(a,c).trim().replace(/\n/g,"\n  ")+(c.compress?"}":"\n}\n")):this.name+" "+this.value.toCSS()+
";\n"},eval:function(a){this.features=this.features&&this.features.eval(a);a.frames.unshift(this);this.ruleset=this.ruleset&&this.ruleset.eval(a);a.frames.shift();return this},variable:function(a){return b.Ruleset.prototype.variable.call(this.ruleset,a)},find:function(){return b.Ruleset.prototype.find.apply(this.ruleset,arguments)},rulesets:function(){return b.Ruleset.prototype.rulesets.apply(this.ruleset)}}})(m("../tree"));(function(b){b.Element=function(a,c,f){this.combinator=a instanceof b.Combinator?
a:new b.Combinator(a);this.value=typeof c==="string"?c.trim():c?c:"";this.index=f};b.Element.prototype.eval=function(a){return new b.Element(this.combinator,this.value.eval?this.value.eval(a):this.value,this.index)};b.Element.prototype.toCSS=function(a){return this.combinator.toCSS(a||{})+(this.value.toCSS?this.value.toCSS(a):this.value)};b.Combinator=function(a){this.value=a===" "?" ":a==="& "?"& ":a?a.trim():""};b.Combinator.prototype.toCSS=function(a){return{"":""," ":" ","&":"","& ":" ",":":" :",
"::":"::","+":a.compress?"+":" + ","~":a.compress?"~":" ~ ",">":a.compress?">":" > "}[this.value]}})(m("../tree"));(function(b){b.Expression=function(a){this.value=a};b.Expression.prototype={eval:function(a){return this.value.length>1?new b.Expression(this.value.map(function(c){return c.eval(a)})):this.value.length===1?this.value[0].eval(a):this},toCSS:function(a){return this.value.map(function(c){return c.toCSS?c.toCSS(a):""}).join(" ")}}})(m("../tree"));(function(b){b.Import=function(a,c,f,d){var k=
this;this.index=d;this._path=a;this.features=f&&new b.Value(f);this.path=a instanceof b.Quoted?/\.(le?|c)ss(\?.*)?$/.test(a.value)?a.value:a.value+".less":a.value.value||a.value;(this.css=/css(\?.*)?$/.test(this.path))||c.push(this.path,function(a,c){if(a)a.index=d;k.root=c||new b.Ruleset([],[])})};b.Import.prototype={toCSS:function(a){a=this.features?" "+this.features.toCSS(a):"";return this.css?"@import "+this._path.toCSS()+a+";\n":""},eval:function(a){var c;this.features&&this.features.eval(a);
if(this.css)return this;else{c=new b.Ruleset([],this.root.rules.slice(0));for(var f=0;f<c.rules.length;f++)c.rules[f]instanceof b.Import&&Array.prototype.splice.apply(c.rules,[f,1].concat(c.rules[f].eval(a)));return this.features?new b.Directive("@media",c.rules,this.features.value):c.rules}}}})(m("../tree"));(function(b){b.JavaScript=function(a,c,b){this.escaped=b;this.expression=a;this.index=c};b.JavaScript.prototype={eval:function(a){var c,f=this,d={},k=this.expression.replace(/@\{([\w-]+)\}/g,
function(c,d){return b.jsify((new b.Variable("@"+d,f.index)).eval(a))});try{k=new Function("return ("+k+")")}catch(h){throw{message:"JavaScript evaluation error: `"+k+"`",index:this.index};}for(var l in a.frames[0].variables())d[l.slice(1)]={value:a.frames[0].variables()[l].value,toJS:function(){return this.value.eval(a).toCSS()}};try{c=k.call(d)}catch(g){throw{message:"JavaScript evaluation error: '"+g.name+": "+g.message+"'",index:this.index};}return typeof c==="string"?new b.Quoted('"'+c+'"',c,
this.escaped,this.index):Array.isArray(c)?new b.Anonymous(c.join(", ")):new b.Anonymous(c)}}})(m("../tree"));(function(b){b.Keyword=function(a){this.value=a};b.Keyword.prototype={eval:function(){return this},toCSS:function(){return this.value},compare:function(a){return a instanceof b.Keyword?a.value===this.value?0:1:-1}};b.True=new b.Keyword("true");b.False=new b.Keyword("false")})(m("../tree"));(function(b){b.mixin={};b.mixin.Call=function(a,c,f,d,k){this.selector=new b.Selector(a);this.arguments=
c;this.index=f;this.filename=d;this.important=k};b.mixin.Call.prototype={eval:function(a){var c,b,d=[],k=!1;for(b=0;b<a.frames.length;b++)if((c=a.frames[b].find(this.selector)).length>0){b=this.arguments&&this.arguments.map(function(c){return c.eval(a)});for(var h=0;h<c.length;h++)if(c[h].match(b,a))try{Array.prototype.push.apply(d,c[h].eval(a,this.arguments,this.important).rules),k=!0}catch(g){throw{message:g.message,index:g.index,filename:this.filename,stack:g.stack,call:this.index};}if(k)return d;
else throw{type:"Runtime",message:"No matching definition was found for `"+this.selector.toCSS().trim()+"("+this.arguments.map(function(a){return a.toCSS()}).join(", ")+")`",index:this.index,filename:this.filename};}throw{type:"Name",message:this.selector.toCSS().trim()+" is undefined",index:this.index,filename:this.filename};}};b.mixin.Definition=function(a,c,f,d){this.name=a;this.selectors=[new b.Selector([new b.Element(null,a)])];this.params=c;this.condition=d;this.arity=c.length;this.rules=f;
this._lookups={};this.required=c.reduce(function(a,c){return!c.name||c.name&&!c.value?a+1:a},0);this.parent=b.Ruleset.prototype;this.frames=[]};b.mixin.Definition.prototype={toCSS:function(){return""},variable:function(a){return this.parent.variable.call(this,a)},variables:function(){return this.parent.variables.call(this)},find:function(){return this.parent.find.apply(this,arguments)},rulesets:function(){return this.parent.rulesets.apply(this)},evalParams:function(a,c){for(var f=new b.Ruleset(null,
[]),d=0,k;d<this.params.length;d++)if(this.params[d].name)if(k=c&&c[d]||this.params[d].value)f.rules.unshift(new b.Rule(this.params[d].name,k.eval(a)));else throw{type:"Runtime",message:"wrong number of arguments for "+this.name+" ("+c.length+" for "+this.arity+")"};return f},eval:function(a,c,f){for(var d=this.evalParams(a,c),k=[],h=0;h<Math.max(this.params.length,c&&c.length);h++)k.push(c[h]||this.params[h].value);d.rules.unshift(new b.Rule("@arguments",(new b.Expression(k)).eval(a)));c=f?this.rules.map(function(a){return new b.Rule(a.name,
a.value,"!important",a.index)}):this.rules.slice(0);return(new b.Ruleset(null,c)).eval({frames:[this,d].concat(this.frames,a.frames)})},match:function(a,c){var b=a&&a.length||0;if(b<this.required)return!1;if(this.required>0&&b>this.params.length)return!1;if(this.condition&&!this.condition.eval({frames:[this.evalParams(c,a)].concat(c.frames)}))return!1;for(var b=Math.min(b,this.arity),d=0;d<b;d++)if(!this.params[d].name&&a[d].eval(c).toCSS()!=this.params[d].value.eval(c).toCSS())return!1;return!0}}})(m("../tree"));
(function(b){b.Operation=function(a,c){this.op=a.trim();this.operands=c};b.Operation.prototype.eval=function(a){var c=this.operands[0].eval(a),a=this.operands[1].eval(a),f;if(c instanceof b.Dimension&&a instanceof b.Color)if(this.op==="*"||this.op==="+")f=a,a=c,c=f;else throw{name:"OperationError",message:"Can't substract or divide a color from a number"};return c.operate(this.op,a)};b.operate=function(a,c,b){switch(a){case "+":return c+b;case "-":return c-b;case "*":return c*b;case "/":return c/
b}}})(m("../tree"));(function(b){b.Paren=function(a){this.value=a};b.Paren.prototype={toCSS:function(a){return"("+this.value.toCSS(a)+")"},eval:function(a){return new b.Paren(this.value.eval(a))}}})(m("../tree"));(function(b){b.Quoted=function(a,c,b,d){this.escaped=b;this.value=c||"";this.quote=a.charAt(0);this.index=d};b.Quoted.prototype={toCSS:function(){return this.escaped?this.value:this.quote+this.value+this.quote},eval:function(a){var c=this,f=this.value.replace(/`([^`]+)`/g,function(d,f){return(new b.JavaScript(f,
c.index,!0)).eval(a).value}).replace(/@\{([\w-]+)\}/g,function(d,f){var h=(new b.Variable("@"+f,c.index)).eval(a);return"value"in h?h.value:h.toCSS()});return new b.Quoted(this.quote+f+this.quote,f,this.escaped,this.index)}}})(m("../tree"));(function(b){b.Rule=function(a,c,f,d,k){this.name=a;this.value=c instanceof b.Value?c:new b.Value([c]);this.important=f?" "+f.trim():"";this.index=d;this.inline=k||!1;this.variable=a.charAt(0)==="@"?!0:!1};b.Rule.prototype.toCSS=function(a){return this.variable?
"":this.name+(a.compress?":":": ")+this.value.toCSS(a)+this.important+(this.inline?"":";")};b.Rule.prototype.eval=function(a){return new b.Rule(this.name,this.value.eval(a),this.important,this.index,this.inline)};b.Shorthand=function(a,c){this.a=a;this.b=c};b.Shorthand.prototype={toCSS:function(a){return this.a.toCSS(a)+"/"+this.b.toCSS(a)},eval:function(){return this}}})(m("../tree"));(function(b){b.Ruleset=function(a,c){this.selectors=a;this.rules=c;this._lookups={}};b.Ruleset.prototype={eval:function(a){var c=
this.selectors&&this.selectors.map(function(c){return c.eval(a)}),c=new b.Ruleset(c,this.rules.slice(0));c.root=this.root;c.allowImports=this.allowImports;a.frames.unshift(c);if(c.root||c.allowImports)for(var f=0;f<c.rules.length;f++)c.rules[f]instanceof b.Import&&Array.prototype.splice.apply(c.rules,[f,1].concat(c.rules[f].eval(a)));for(f=0;f<c.rules.length;f++)if(c.rules[f]instanceof b.mixin.Definition)c.rules[f].frames=a.frames.slice(0);for(f=0;f<c.rules.length;f++)c.rules[f]instanceof b.mixin.Call&&
Array.prototype.splice.apply(c.rules,[f,1].concat(c.rules[f].eval(a)));for(var f=0,d;f<c.rules.length;f++)d=c.rules[f],d instanceof b.mixin.Definition||(c.rules[f]=d.eval?d.eval(a):d);a.frames.shift();return c},match:function(a){return!a||a.length===0},variables:function(){return this._variables?this._variables:this._variables=this.rules.reduce(function(a,c){c instanceof b.Rule&&c.variable===!0&&(a[c.name]=c);return a},{})},variable:function(a){return this.variables()[a]},rulesets:function(){return this._rulesets?
this._rulesets:this._rulesets=this.rules.filter(function(a){return a instanceof b.Ruleset||a instanceof b.mixin.Definition})},find:function(a,c){var c=c||this,f=[],d=a.toCSS();if(d in this._lookups)return this._lookups[d];this.rulesets().forEach(function(d){if(d!==c)for(var h=0;h<d.selectors.length;h++)if(a.match(d.selectors[h])){a.elements.length>d.selectors[h].elements.length?Array.prototype.push.apply(f,d.find(new b.Selector(a.elements.slice(1)),c)):f.push(d);break}});return this._lookups[d]=f},
toCSS:function(a,c){var f=[],d=[],k=[],h=[],g;this.root||(a.length===0?h=this.selectors.map(function(a){return[a]}):this.joinSelectors(h,a,this.selectors));for(var n=0;n<this.rules.length;n++)g=this.rules[n],g.rules||g instanceof b.Directive?k.push(g.toCSS(h,c)):g instanceof b.Comment?g.silent||(this.root?k.push(g.toCSS(c)):d.push(g.toCSS(c))):g.toCSS&&!g.variable?d.push(g.toCSS(c)):g.value&&!g.variable&&d.push(g.value.toString());k=k.join("");this.root?f.push(d.join(c.compress?"":"\n")):d.length>
0&&(h=h.map(function(a){return a.map(function(a){return a.toCSS(c)}).join("").trim()}).join(c.compress?",":",\n"),f.push(h,(c.compress?"{":" {\n  ")+d.join(c.compress?"":"\n  ")+(c.compress?"}":"\n}\n")));f.push(k);return f.join("")+(c.compress?"\n":"")},joinSelectors:function(a,c,b){for(var d=0;d<b.length;d++)this.joinSelector(a,c,b[d])},joinSelector:function(a,c,f){for(var d=[],g=[],h=[],l=[],n=!1,o,j=0;j<f.elements.length;j++)o=f.elements[j],o.combinator.value.charAt(0)==="&"&&(n=!0),n?l.push(o):
h.push(o);n||(l=h,h=[]);h.length>0&&d.push(new b.Selector(h));l.length>0&&g.push(new b.Selector(l));for(f=0;f<c.length;f++)a.push(d.concat(c[f]).concat(g))}}})(m("../tree"));(function(b){b.Selector=function(a){this.elements=a;if(this.elements[0].combinator.value==="")this.elements[0].combinator.value=" "};b.Selector.prototype.match=function(a){var c=this.elements.length,b=a.elements.length,d=Math.min(c,b);if(c<b)return!1;else for(c=0;c<d;c++)if(this.elements[c].value!==a.elements[c].value)return!1;
return!0};b.Selector.prototype.eval=function(a){return new b.Selector(this.elements.map(function(b){return b.eval(a)}))};b.Selector.prototype.toCSS=function(a){return this._css?this._css:this._css=this.elements.map(function(b){return typeof b==="string"?" "+b.trim():b.toCSS(a)}).join("")}})(m("../tree"));(function(b){b.URL=function(a,b){if(a.data)this.attrs=a;else{if(typeof window!=="undefined"&&!/^(?:https?:\/\/|file:\/\/|data:|\/)/.test(a.value)&&b.length>0)a.value=b[0]+(a.value.charAt(0)==="/"?
a.value.slice(1):a.value);this.value=a;this.paths=b}};b.URL.prototype={toCSS:function(){return"url("+(this.attrs?"data:"+this.attrs.mime+this.attrs.charset+this.attrs.base64+this.attrs.data:this.value.toCSS())+")"},eval:function(a){return this.attrs?this:new b.URL(this.value.eval(a),this.paths)}}})(m("../tree"));(function(b){b.Value=function(a){this.value=a;this.is="value"};b.Value.prototype={eval:function(a){return this.value.length===1?this.value[0].eval(a):new b.Value(this.value.map(function(b){return b.eval(a)}))},
toCSS:function(a){return this.value.map(function(b){return b.toCSS(a)}).join(a.compress?",":", ")}}})(m("../tree"));(function(b){b.Variable=function(a,b,f){this.name=a;this.index=b;this.file=f};b.Variable.prototype={eval:function(a){var c,f,d=this.name;d.indexOf("@@")==0&&(d="@"+(new b.Variable(d.slice(1))).eval(a).value);if(c=b.find(a.frames,function(b){if(f=b.variable(d))return f.value.eval(a)}))return c;else throw{type:"Name",message:"variable "+d+" is undefined",filename:this.file,index:this.index};
}}})(m("../tree"));(function(b){b.find=function(a,b){for(var f=0,d;f<a.length;f++)if(d=b.call(a,a[f]))return d;return null};b.jsify=function(a){return Array.isArray(a.value)&&a.value.length>1?"["+a.value.map(function(a){return a.toCSS(!1)}).join(", ")+"]":a.toCSS(!1)}})(m("./tree"));(function(){var b=m("path"),a=m("util"),c=m("fs"),f={version:[1,2,1],Parser:m("./parser").Parser,importer:m("./parser").importer,tree:m("./tree"),render:function(a,b,c){b=b||{};typeof b==="function"&&(c=b,b={});var d=
new f.Parser(b),g;if(c)d.parse(a,function(a,d){c(a,d&&d.toCSS&&d.toCSS(b))});else return g=new (m("events").EventEmitter),process.nextTick(function(){d.parse(a,function(a,c){a?g.emit("error",a):g.emit("success",c.toCSS(b))})}),g},writeError:function(b,c){var c=c||{},d="",g=b.extract,m=[],j=c.color?f.stylize:function(a){return a};if(!c.silent){if(b.stack)return a.error(j(b.stack,"red"));if(!b.hasOwnProperty("index"))return a.error(b.stack||b.message);typeof g[0]==="string"&&m.push(j(b.line-1+" "+g[0],
"grey"));g[1]&&m.push(b.line+" "+g[1].slice(0,b.column)+j(j(j(g[1][b.column],"bold")+g[1].slice(b.column+1),"red"),"inverse"));typeof g[2]==="string"&&m.push(j(b.line+1+" "+g[2],"grey"));m=m.join("\n")+"\u001b[0m\n";d+=j(b.type+"Error: "+b.message,"red");b.filename&&(d+=j(" in ","red")+b.filename+j(":"+b.line+":"+b.column,"grey"));a.error(d,m);b.callLine&&(a.error(j("from ","red")+(b.filename||"")),a.error(j(b.callLine,"grey")+" "+b.callExtract))}}};"color,directive,operation,dimension,keyword,variable,ruleset,element,selector,quoted,expression,rule,call,url,alpha,import,mixin,comment,anonymous,value,javascript,assignment,condition,paren".split(",").forEach(function(a){m("./tree/"+
a)});f.Parser.importer=function(a,d,g,m){var o;d.unshift(".");for(var j=0;j<d.length;j++)try{o=b.join(d[j],a);c.statSync(o);break}catch(i){o=null}o?c.readFile(o,"utf-8",function(a,c){if(a)return g(a);(new f.Parser({paths:[b.dirname(o)].concat(d),filename:o})).parse(c,function(a,b){g(a,b,c)})}):typeof m.errback==="function"?m.errback(a,d,g):g({type:"File",message:"'"+a+"' wasn't found.\n"})};m("./functions");m("./colors");for(var d in f)exports[d]=f[d];f.stylize=function(a,b){var c={bold:[1,22],inverse:[7,
27],underline:[4,24],yellow:[33,39],green:[32,39],red:[31,39],grey:[90,39]};return"\u001b["+c[b][0]+"m"+a+"\u001b["+c[b][1]+"m"}})();(function(){var b=m("path"),a=m("fs"),c=m("util"),f=m("os"),d=m("../lib/less"),g=process.argv.slice(1),h={compress:!1,yuicompress:!1,optimization:1,silent:!1,paths:[],color:!0},g=g.filter(function(a){var g;if(g=a.match(/^-I(.+)$/))return h.paths.push(g[1]),!1;if(g=a.match(/^--?([a-z][0-9a-z-]*)(?:=([^\s]+))?$/i))a=g[1];else return a;switch(a){case "v":case "version":c.puts("lessc "+
d.version.join(".")+" (LESS Compiler) [JavaScript]"),process.exit(0);case "verbose":h.verbose=!0;break;case "s":case "silent":h.silent=!0;break;case "h":case "help":c.puts("usage: lessc source [destination]"),process.exit(0);case "x":case "compress":h.compress=!0;break;case "yui-compress":h.yuicompress=!0;break;case "no-color":h.color=!1;break;case "include-path":h.paths=g[2].split(f.type().match(/Windows/)?";":":").map(function(a){if(a)return b.resolve(process.cwd(),a)});break;case "O0":h.optimization=
0;break;case "O1":h.optimization=1;break;case "O2":h.optimization=2}}),l=g[1];l&&l!="-"&&(l=b.resolve(process.cwd(),l));var n=g[2];n&&(n=b.resolve(process.cwd(),n));var o,j;l||(c.puts("lessc: no input files"),process.exit(1));var i=function(f,g){f&&(c.puts("lessc: "+f.message),process.exit(1));(new d.Parser({paths:[b.dirname(l)].concat(h.paths),optimization:h.optimization,filename:l})).parse(g,function(b,f){if(b)d.writeError(b,h),process.exit(1);else try{o=f.toCSS({compress:h.compress,yuicompress:h.yuicompress}),
n?(j=a.openSync(n,"w"),a.writeSync(j,o,0,"utf8")):c.print(o)}catch(g){d.writeError(g,h),process.exit(2)}})};if(l!="-")a.readFile(l,"utf-8",i);else{process.stdin.resume();process.stdin.setEncoding("utf8");var q="";process.stdin.on("data",function(a){q+=a});process.stdin.on("end",function(){i(!1,q)})}})()})(require);
